In [9]:
## Exo 1

import numpy as np

A = np.array ([ [3,41,5], [9, 58, -1], [110, 122 ,2] ])
B = np.array ([ [81, -1, 8], [23, 1, 3], [187, 2, 32] ])

C= A + B
print("A : ", A)
print("B : ", B)
print("A + B : ", C)

A :  [[  3  41   5]
 [  9  58  -1]
 [110 122   2]]
B :  [[ 81  -1   8]
 [ 23   1   3]
 [187   2  32]]
A + B :  [[ 84  40  13]
 [ 32  59   2]
 [297 124  34]]


In [14]:
## Exo 2

import numpy as np
 
A = np.array ([ [3,41,5], [9, 58, -1], [110, 122 ,2] ])
B = np.array ([ [81, -1, 8], [23, 1, 3], [187, 2, 32] ])
 
C = A.dot(B)

print("A : ", A)
print("B : ", B)
print("A * B : ", C)

A :  [[  3  41   5]
 [  9  58  -1]
 [110 122   2]]
B :  [[ 81  -1   8]
 [ 23   1   3]
 [187   2  32]]
A * B :  [[ 2121    48   307]
 [ 1876    47   214]
 [12090    16  1310]]


In [18]:
## Exo 3

def eststochastique(P):
    x=np.sum(P,axis=1)
    
    etat=(x < 1).all()       
    return etat
 
    
def estbistochastique(P):
    if(eststochastique(P)):
        x=np.sum(P,axis=1)
    return etat
 

def vecteurstable(G, h):
    if(eststochastique(G)):
        x=np.sum(G,axis=1)
    return etat

In [13]:
## Exo 4

import numpy as np

A = np.array ([ [3,41,5], [9, 58, -1], [110, 122 ,2] ])

C = A.transpose()

print("A : ", A)
print("Transposée de A : ", C)

A :  [[  3  41   5]
 [  9  58  -1]
 [110 122   2]]
Transposée de A :  [[  3   9 110]
 [ 41  58 122]
 [  5  -1   2]]


In [19]:
## Exo 5

def permut(A, perm, N):
    B = np.empty_like(A)
    for i in range(N):
        B[A[:] == i] = perm[i]
    return B